@startuml

start
scale 500 width


partition "App Authorization" {
    :Obtain authorization token;
    note right
        e.g., SMART on FHIR OAuth
    end note
}

partition "Establish EHR Patient ID" {
    if (Authorization context?) then (yes)
        :Read patient ID
         from authorization context;
        note right
            e.g., SMART's launch/patient
        end note
    else (no)
        :Obtain patient ID
         (e.g., FHIR Patient Search);
    endif
}

partition "Learn Submission Preferences" {
    if (Use ServiceRequest?) then (yes)
        :Read ServiceRequest resource
         with "standing order" tag;
        :Extract submission preferences;
        note right
            e.g., every 2 weeks        
        end note
    else (no)
        :Obtain submission preferences
         out-of-band (through user interaction
         or external configuration);
    endif
}

partition "Submission Triggers" {
    split
        :Scheduled Submission Interval;
    split again
        :One-Time Orders;
        note right
            User initiated
            (e.g., in-app button)
        end note
    end split
}

:Prepare FHIR Bundle
 with CGM data;
 
:POST Bundle
 to EHR;
note right 
    Using authorization token
    (e.g., SMART on FHIR Access Token)
end note

stop

@enduml